# Comprehensive Backup Konfigurasjonen

# Backup-strategi
backup_strategy: "selective"

# VSCode-spesifikk konfigurasjon
vscode_config:
  profiles: 
    - "Library/Application Support/Code/User/profiles"
  extensions:
    - "Continue"
    - "User/settings.json"
    - "User/keybindings.json"

# Områder som skal inkluderes
include:
  - Documents
  - .ssh
  - .config
  - .continue
  - .zshrc
  - .gitconfig
  - .env
  - Library/Application Support/Code
  - Library/Application Support/Claude
  - Library/Application Support/ChatGPT
  - Library/Application Support/Sublime*
  - Library/Application Support/Joplin
  - tmp

# Områder som skal ekskluderes
exclude:
  # Library-mapper som kan ekskluderes
  - Library/Application Support/*
  - Library/Caches
  - Library/Logs
  - Library/Developer
  - Library/CloudStorage
  - Library/Preferences
  - Library/Safari
  - Library/Mail
  - Library/Messages

  # Unødvendige mapper
  - .Trash
  - .cache/huggingface
  - .npm
  - node_modules
  - .gradle
  - .maven
  - .espressif
  - .pyenv
  - .android
  - .local/share/Trash
  - "**/.cache/huggingface/**"


  # Mappa med backups:
  - vscode/mackup/backups

  # Midlertidige mapper
  - "**/build"
  - "**/dist"
  - "**/*.tmp"
  - "**/*.temp"

  # Tokens og sensitive data
#  - .token_huggingface
#  - .token_grog

# Sikkerhet og systemdetaljer
system_info:
  collect: true
  include:
    - os_version
    - hardware_info
    - installed_apps
    - network_config

# Backup-innstillinger
incremental: true
verify_after_backup: true
compress_after_days: 7
max_backups: 5

# Spesielle tilfeller
special_cases:
  JoplinBackup:
    source: "~/JoplinBackup"
    destination: "~/Documents/joplineksport"
    only_latest: true
