# default-config.yaml
# Dette er liksom fallback-konfigurasjonen om du ikke har en config.yaml. 
# Du kan selvsagt bare bruke denne, men altså da kan det være at du har lyst til å redigere litt på den.
# Eller på config.yaml
# Navn på klient/maskin (kan bli oppdatert dynamisk)
client_name: Default-Client

# Standardmapper som skal inkluderes i backup
include:
  - Documents
  - Downloads
  - Pictures
  - Music
  - Movies
  - .ssh
  - .config
  - .zshrc
  - .bashrc
  - .bash_profile
  - .gitconfig
  - .env
  - Library/Application Support/Code/User

# Standardmapper som skal ekskluderes fra backup
exclude:
  - Library
  - .zsh_sessions
  - Applications
  - Desktop
  - Public

# Standard inkrementell backup-innstilling
incremental: false
