# Standard backup-konfigurasjon

# Grunnleggende konfigurasjon
backup_strategy: "comprehensive"  # 'comprehensive' eller 'selective'

# System info som skal samles ved backup
system_info:
  collect: true
  include:
    - os_version
    - hardware_info
    - installed_apps
    - network_config
    - disk_usage
    - mounted_volumes

# Konfigurasjon for comprehensive backup
comprehensive_exclude:
  # Systemmapper
  - "Library/Caches"
  - "Library/Logs"
  - ".Trash"
  - ".cache/**"
  - ".espressif"
  - ".local/share/Trash"
  
  # Utviklingsmiljø
  - "node_modules"
  - ".npm"
  - ".maven"
  - ".gradle"
  - "**/venv"
  - "**/env"
  - "**/.venv"
  - "**/build"
  - "**/dist"
  
  # Temporære filer
  - "**/*.tmp"
  - "**/*.temp"
  - "**/*.swp"
  - "**/*~"
  
  # Store applikasjonsmapper
  - "Library/Application Support/Steam"
  - "Library/Developer/Xcode/iOS DeviceSupport"
  - "Library/Developer/Xcode/DerivedData"
  - "Library/CloudStorage"


# Filer som alltid skal inkluderes
force_include:
  - ".ssh/**"
  - ".gitconfig"
  - ".zshrc"
  - ".bashrc"
  - ".bash_profile"
  - "Documents/**"

# Konfigurasjon for selective backup
include:
  - Documents
  - Downloads
  - Pictures
  - Music
  - .ssh
  - .config
  - .zshrc
  - .bashrc
  - .bash_profile
  - .gitconfig
  - .env
  - Library/Application Support/Code/User

exclude:
  - Library
  - .zsh_sessions
  - Applications
  - Desktop
  - Public
  - .cache
  - .espressif
  - .vscode

special_cases:
  JoplinBackup:
    source: "~/JoplinBackup"
    destination: "~/Documents/joplineksport"
    only_latest: true

# Sikkerhet og systemdetaljer
system_info:
  collect: true
  include:
    - os_version
    - hardware_info
    - installed_apps
    - network_config

# Backup-innstillinger
incremental: true # Inkrementell backup
verify_after_backup: true # Verifiser backup etter at den er fullført
compress_after_days: 7 # Dager
max_backups: 10 # Antall
backup_retention: 30 # Dager